"""Fully offline model stand-ins (``AGENT_LLM_PROVIDER=mock``).

They let the whole team run - and be tested - without any API key: the planner
echoes the real goal, the actor writes real files through the real tools, the
reviewer approves (or rejects in "strict" mode) and the tester runs real pytest.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from typing import Any

from .client import ScriptedLLM

HELLO_MODULE = '''"""Greeting helpers (generated by the agentteam mock provider)."""

from __future__ import annotations


def greet(name: str) -> str:
    """Return a friendly greeting for *name*."""

    if not isinstance(name, str):
        raise TypeError("name must be a str")
    cleaned = name.strip() or "world"
    return f"Hello, {cleaned}!"


if __name__ == "__main__":
    print(greet("world"))
'''

HELLO_TEST = '''import pytest

from hello import greet


def test_greet_returns_greeting() -> None:
    assert greet("world") == "Hello, world!"


def test_greet_strips_whitespace() -> None:
    assert greet("  cline  ") == "Hello, cline!"


def test_greet_defaults_to_world() -> None:
    assert greet("   ") == "Hello, world!"


def test_greet_rejects_non_str() -> None:
    with pytest.raises(TypeError):
        greet(42)  # type: ignore[arg-type]
'''

APPROVE_REVIEW: dict[str, Any] = {
    "approved": True,
    "score": 8,
    "issues": [],
    "suggestions": ["可以为 greet 增加类型检查的边界用例，并补充模块级 docstring。"],
}

REJECT_REVIEW: dict[str, Any] = {
    "approved": False,
    "score": 3,
    "issues": ["greet 缺少非字符串输入的防御性处理。", "测试没有覆盖空字符串场景。"],
    "suggestions": ["补充类型校验与空字符串用例后再提交。"],
}

TESTER_SUMMARY: dict[str, Any] = {"summary": "pytest 已运行，退出码与输出一致。"}


def _goal_from(messages: Sequence[dict[str, str]] | None) -> str:
    text = (messages or [{}])[-1].get("content", "") if messages else ""
    match = re.search(r"目标[:：]\s*(.+)", text)
    return match.group(1).strip().splitlines()[0] if match else "实现目标"


def planner_response(messages: Sequence[dict[str, str]] | None = None) -> dict[str, Any]:
    goal = _goal_from(messages)
    return {
        "goal": goal,
        "summary": "离线 mock 计划：先写出可运行模块，再补上 pytest 用例，最后跑测试验证。",
        "steps": [
            {
                "id": 1,
                "title": "实现模块",
                "detail": "创建 hello.py，实现 greet(name)，包含输入校验与 __main__ 演示。",
                "files": ["hello.py"],
            },
            {
                "id": 2,
                "title": "编写测试",
                "detail": "创建 test_hello.py，覆盖正常值、空格裁剪、空串兜底与非法类型。",
                "files": ["test_hello.py"],
            },
        ],
        "test_commands": ["python -m pytest -q -p no:cacheprovider test_hello.py"],
        "acceptance": ["hello.py 与 test_hello.py 均存在", "pytest 全部用例通过"],
    }


def actor_response(messages: Sequence[dict[str, str]] | None = None) -> dict[str, Any]:
    """Writes both files in a single iteration: proof that tools really run."""

    return {
        "thought": "两个文件相互独立，一次性写入以减少往返。",
        "actions": [
            {"tool": "file.write", "args": {"path": "hello.py", "content": HELLO_MODULE}},
            {"tool": "file.write", "args": {"path": "test_hello.py", "content": HELLO_TEST}},
        ],
        "steps_completed": [1, 2],
        "done": True,
        "summary": "已创建 hello.py（greet 实现）与 test_hello.py（4 个用例）。",
    }


def mock_clients(*, strict_first_review: bool = False) -> dict[str, ScriptedLLM]:
    """One deterministic client per role."""

    reviewer_script: list[Any] = [REJECT_REVIEW, APPROVE_REVIEW] if strict_first_review else [APPROVE_REVIEW]
    return {
        "planner": ScriptedLLM([planner_response], model="mock-planner"),
        "actor": ScriptedLLM([actor_response], model="mock-actor"),
        "reviewer": ScriptedLLM(reviewer_script, model="mock-reviewer"),
        "tester": ScriptedLLM([TESTER_SUMMARY], model="mock-tester"),
    }
